### ISSUE TITLE
Download link of VCTK is not working

### ISSUE THREAD

**Issue by jhauret** [urgent-challenge/urgent2024_challenge#11]
The download link of VCTK, used in [this script](https://github.com/urgent-challenge/urgent2024_challenge/blob/25cf0dd0453ebf8e1acc0aaf58848536bbf51e3e/utils/prepare_VCTK_speech.sh#L18C18-L18C71), seems to be dead: https://datashare.ed.ac.uk/download/DS_10283_3443.zip

Do you have another alternative?

**Comment by Emrys365** [comment]
Hi @jhauret, the website was only temporarily down yesterday. Now it should be working.
