### ISSUE TITLE
A bug in `simulation/rir_utils.py`

### ISSUE THREAD

**Issue by Dahan-Wang** [urgent-challenge/urgent2024_challenge#6]
After running the prepare_espnet_data.sh script to generate the validation set, we encountered an issue where the clean speech exhibited a significant level of reverberation, almost akin to that found in noisy speech samples.

We found there might be a bug located in `simulation/rir_utils.py` at Line `15`: `early_rir_samples = int(early_rir_ms * fs)`.
It appears that `early_rir_ms` should first be converted into seconds before being multiplied by `fs`. If not, `early_rir_samples` ends up representing 50 **seconds** of early reverberation, which seems incorrect. 

Could you please check this section of the code?

**Comment by Emrys365** [comment]
Hi @Dahan-Wang, thanks a lot for your report! You're right. I have updated the code and verified that the issue is addressed now. The clean speech should now be no long highly reverberant.

Again, sorry about this careless bug! We will notify other participants about it.
